server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/Songs
    username: ${name:root}
    password: ${password:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dll-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
s3bucket:
  name: songs-bucket
  region: us-east-1
  endpoint: http://${AWS_HOST:localhost}:4566/
rabbitmq:
  queueName: downloaded
  exchange: downloaded-exc
  routingKey: downloaded-rKey
messageService:
  maxRetries: 3